### PR TITLE
XAUR Second draft

### PR DESCRIPTION
**Pull request by RealJoshue108**
Hi @michael-n-cooper This is the XAUR second draft branch to be merged into master. I will then mind a publication branch. Thanks Josh

### CODE REVIEW

**Review by michael-n-cooper — CHANGES_REQUESTED** [review]
The first paragraph of the status belongs in the publication branch and shouldn't be merged into master. So please remove it before merge, and replace it in the publication branch. As a first look, the para looks good though.

The rest of the doc looks good to merge, so go ahead after that change.

**Comment by RealJoshue108** [comment]
Thanks @michael-n-cooper - done. I left the paragraph "To comment on this draft [...]" please confirm if that is ok, or should go into publication branch.

**Comment by michael-n-cooper** [comment]
Do leave the comment paragraph in the editors' draft, it's useful there. 
Michael

**Comment by RealJoshue108** [comment]
Ok great - then this is good to be merged. @michael-n-cooper

**Review by gtothe7 — COMMENTED** [review]
#124

**Pull request merged**
