### PR TITLE
Fresh PR with updated RAUR user needs and biblio refs

### PR DESCRIPTION
**Pull request by RealJoshue108**
Hi @michael-n-cooper,

This is good to be merged into master and then I can mint a publication branch.

NOTE:  ReSpec is complaining:

"Please migrate to "respec-w3c" profile." - which I don't know how to fix.

Any other issues please let me know, thanks.

Josh

### CODE REVIEW

**Review by michael-n-cooper — CHANGES_REQUESTED** [review]
Taking a quick look:

You can fix the respec warning by changing the link to load respec from "respec-w3c-common" to "respec-w3c".

There are validation errors in the rtc/index.html file, which means it's not ready to merge. You'll need to go through it.

The Status section also has a new paragraph that doesn't belong in the editors' draft.

A big issue is there are two versions of the RAUR in this branch, one in raur and one in rtc. I remember deleting the rtc branch. From what I can tell looking into it quickly, you continued work in the AccessibleRTC branch instead of creating a new working branch off master. Therefore your branch does not update the latest copy, and could cause all sorts of problems. if you're lucky, you may be able to merge master into your branch, and all will be well. If you're unlucky, you'll need to create a new working branch off master and redo your edits in that.

In the future, as we've discussed, it's really important a) to create a new working branch off master each time you're doing edits, rather than work off a long-lived working branch; b) merge edits more frequently instead if in a massive pull request, so review can be more effective and risk of edit collision is reduced.

**Comment by RealJoshue108** [comment]
>You can fix the respec warning by changing the link to load respec from "respec-w3c-common" to >"respec-w3c".

Ok, great.

>There are validation errors in the rtc/index.html file, which means it's not ready to merge. You'll need to >go through it.

Will have a look.

>A big issue is there are two versions of the RAUR in this branch, one in raur and one in rtc. I remember >deleting the rtc branch. From what I can tell looking into it quickly, you continued work in the >AccessibleRTC branch instead of creating a new working branch off master.

Yes, I have successfully merged from master into the AccessibleRTC branch, so I continued to work in it in the 'raur' directory.

Suggested change in working methods noted, thanks.

**Comment by RealJoshue108** [comment]
@michael-n-cooper I've uploaded a validated file (thanks for the head up) - there are still a couple of minor warnings around the use of <code><section></code> elements needing to be wrapped in headings but don't think this is sensible to do in this context. 

I also removed the use of the <div class="note"> stuff which has the "auto generated id" (with the associated aria=heading etc) and I've just used a <p class="note"> which I think is semantically better for the note content. ReSpec seems to insert a <div> with a role heading above this node when the class it declared.

Regarding the extra paragraph - I'm not sure what you are referring to? It looks like something may be generated when the sotd class is declared. So please be more specific, or let me know where I can make an edit to what the sotd class outputs.

I've also fixed the previous ReSpec error but then there was another generated:

>Configuration options wg, wgURI, wgId, wgPatentURI, and wgPatentPolicy are deprecated. Please use the group option instead.

I then used the group option in the respec-config file and this seems to have fixed it.

**Comment by RealJoshue108** [comment]
@michael-n-cooper Also I'm working here:

~/w3c/apa/AccessibleRTC/raur/index.html

and not:

~/w3c/apa/AccessibleRTC/rtc/index.html

So I've not fixed any validation errors etc in the rtc/index.html dir.

**Comment by RealJoshue108** [comment]
Hey @michael-n-cooper I hope this is in better shape and should merge ok (mystery paragraph not with standing). If not let me know and I can delete the AccessibleRTC branch which contains the dir I've been working in (~/w3c/apa/AccessibleRTC/raur/index.html), mint another branch and work there if you need that. Travis tests seem ok - but please let me know, thanks (am clocking out for evening now).

**Comment by RealJoshue108** [comment]
@michael-n-cooper I've removed the rtc dir in this branch, as well as the <p> relating to comments, thanks.

**Comment by RealJoshue108** [comment]
@michael-n-cooper I've added a commit to fix validation errors - please do check and let me know if ok 

39e799e6a71f1908c6fd46091f71508ee01ffd7a

**Pull request merged**
